heat_template_version: 2015-10-15
description: Simple Template
resources:
  my_vm1:
    type: OS::Nova::Server
    properties:
      key_name: host
      image: cirros
      flavor: m1.tiny
      name: vm1
      user_data_format: RAW
      user_data: |
        #!/bin/sh
        echo '192.168.1.1 router' >> /etc/hosts
  my_vm2:
    type: OS::Nova::Server
    properties:
      key_name: host
      image: cirros
      flavor: m1.tiny
      name: vm2
      user_data_format: RAW
      user_data: |
        #!/bin/sh
        echo '192.168.1.1 router' >> /etc/hosts
